### ISSUE TITLE
New account creation/login and demo account (4/5/2018, 2 days)

### ISSUE THREAD

**Issue by JonHalloran** [JonHalloran/Mercury#3]
- [ ]  Allow users to create and login
- [ ]  Have a demo login
- [ ]  Some feature are off limits to people not logged in
- [ ]  Adequate styling
- [ ]  Smooth, bug-free navigation
- [ ]  Seeded with info to demonstrate this feature

**Comment by AAlfarho** [comment]
Great job on the user auth, a couple of details to address before closing this MVP.

- [x] Let's give the logo on the navbar an action to redirect to our splash/homepage.
- [x] The text and the hero image don't really play along together, the text is lost to the image. I would suggest updating the content of the text too.
    ![screen shot 2018-04-06 at 9 56 51 am](https://user-images.githubusercontent.com/1103663/38433740-e55d11a8-3980-11e8-9946-450f7ee34e7f.png)
- [x] I noticed that when accessing the root URL `https://mercury-jh.herokuapp.com/` we are redirected to our `#/login`, how will the hero/splash (`/#/`)  screen be accessed?
- [x] Let's add some spacing on the error display, maybe even centering them?
   ![screen shot 2018-04-06 at 10 01 25 am](https://user-images.githubusercontent.com/1103663/38433984-b505c67a-3981-11e8-8097-4d9265577ff8.png)
- [x] Let's add some spacing on the input too, the placeholder text and the actual input are not properly aligned.
  ![screen shot 2018-04-06 at 10 05 33 am](https://user-images.githubusercontent.com/1103663/38434141-31c2412a-3982-11e8-96b4-84a10b599291.png)

Only a couple of cosmetic additions before closing this MVP.

Assign this issue back to me once the updates addressing these issues are live in Heroku.

**Comment by AAlfarho** [comment]
- [x] There seems to be an issue clearing the errors. 
   + Try to sign up an invalid user, errors will be displayed.
   + Click the `Login` link.
   + Errors from the signup are carried over to the login component.
- [x] SIgnup form has a `Login` button rather than a `Sign Up`  value.
- [x] We are missing matching styles on the login form.
   + Login 
         ![screen shot 2018-04-09 at 10 39 21 am](https://user-images.githubusercontent.com/1103663/38513222-60d874d6-3be2-11e8-89c5-08d2135acf2d.png)
   + Signup
         ![screen shot 2018-04-09 at 10 40 50 am](https://user-images.githubusercontent.com/1103663/38513272-7fa53296-3be2-11e8-9346-51efb6503a69.png)
- [x] I would suggest adding a radius to the buttons so they don't look all _squared_.


Assign this issue back to me once the updates addressing these issues are live in Heroku.

**Comment by AAlfarho** [comment]
The latest update to Heroku addresses the feedback here mentioned, this MVP is now closed.
